from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class CampaignRepositoryPort(Protocol):
    async def get_events(self, campaign_id: str) -> list[Any]: ...
    async def save_events(self, campaign_id: str, events: list[Any]) -> None: ...
    async def create(self, campaign_id: str) -> None: ...
    async def list(self) -> list[str]: ...
    async def delete(self, campaign_id: str) -> None: ...
    async def exists(self, campaign_id: str) -> bool: ...
