from collections.abc import Mapping
from typing import Any, Generic, Protocol, TypeVar, runtime_checkable

T = TypeVar("T")


@runtime_checkable
class KeyValueStorePort(Protocol, Generic[T]):
    async def get(self, key: str) -> T | None: ...
    async def set(self, key: str, value: T) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def clear(self) -> None: ...


@runtime_checkable
class VectorStorePort(Protocol):
    async def add(
        self,
        doc_id: str,
        vector: list[float],
        metadata: dict[str, Any] | None = None,
    ) -> None: ...
    async def get(self, doc_id: str) -> list[float] | None: ...
    async def search(self, vector: list[float], limit: int = 5) -> list[str]: ...
    async def clear(self) -> None: ...
    async def keys(self) -> list[str]: ...


@runtime_checkable
class DocumentStorePort(Protocol):
    async def set(self, key: str, value: Mapping[str, Any]) -> None: ...
    async def get(self, key: str) -> dict[str, Any] | None: ...
    async def clear(self) -> None: ...


@runtime_checkable
class MetadataStorePort(Protocol):
    async def set(self, key: str, value: dict[str, Any]) -> None: ...
    async def get(self, key: str) -> dict[str, Any] | None: ...
    async def clear(self) -> None: ...


@runtime_checkable
class TokenStorePort(Protocol):
    async def set(self, key: str, value: Any) -> None: ...
    async def get(self, key: str) -> Any: ...
    async def clear(self) -> None: ...
