from __future__ import annotations

from typing import Any, Protocol


class NarrativePromptBuilderContract(Protocol):
    def build_system_prompt(self, scene_type: str | None = None) -> str: ...
    def build_user_prompt(self, ctx: dict[str, Any], action: str) -> str: ...
    def get_generation_config(self, scene_type: str | None) -> dict[str, Any]: ...
    def sanitize_output(self, text: str) -> str: ...
    def normalize_action(self, action: str) -> str: ...
    def enforce_length(self, text: str, max_chars: int) -> str: ...


class SessionSummaryPromptContract(Protocol):
    def extract(self, events: list[dict]) -> str: ...
    def build_prompt(self, text: str) -> str: ...
